# Generated by Django 5.1.3 on 2024-11-10 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('product_name', models.TextField()),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
